package com.proxgrind.chameleon.defined;

public enum ChameleonCMDSet {
    HELP,
    GET_VERSION,
    RESET_DEVICE,

    GET_MEMORY_SIZE,
    GET_UID_SIZE,

    SET_CONFIG,
    QUERY_CONFIG,
    CONFIG_HELP,

    QUERY_UID,
    SET_UID,

    QUERY_READONLY,
    SET_READONLY,

    UPLOAD_XMODEM,
    DOWNLOAD_XMODEM,

    GET_ACTIVE_SLOT,
    SET_ACTIVE_SLOT,
    CLEAR_ACTIVE_SLOT,

    GET_RIGHT_BUTTON_CLICK,
    SET_RIGHT_BUTTON_CLICK,
    BUTTON_RIGHT_CLICK_HELP,

    GET_LEFT_BUTTON_CLICK,
    SET_LEFT_BUTTON_CLICK,
    BUTTON_LEFT_CLICK_HELP,

    GET_RIGHT_BUTTON_LONG_CLICK,
    SET_RIGHT_BUTTON_LONG_CLICK,
    BUTTON_RIGHT_CLICK_LONG_HELP,

    GET_LEFT_BUTTON_LONG_CLICK,
    SET_LEFT_BUTTON_LONG_CLICK,
    BUTTON_LEFT_CLICK_LONG_HELP,

    GET_RSSI_VOLTAGE,
    UPLOAD_ENCRYPTED,
    DETECTION,
    DETECTION_CLEAR,

    GET_SAKMODE,
    SET_SAKMODE,
    GET_SAKMODE_HELP,

    GET_UIDMODE,
    SET_UIDMODE,
    GET_UIDMODE_HELP,

    GET_TIMEOUT,
    SET_TIMEOUT,
    GET_TIMEOUT_HELP,

    GETUID_READER,
    KEYAUTH,
    SETKEY,
    GENKEY,

    CLONE,
}
